In [1]:
### Libraries USed Tensorflow> 2.0  and keras


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
#### vocabulary size
voc_size = 10000

# One hot representation

In [11]:
#getting the onehot representation of each word in the sent
onehot_representation= [one_hot(words, voc_size) for words in sent]
print(onehot_representation)

[[9231, 8594, 2528, 9298], [9231, 8594, 2528, 3828], [9231, 1493, 2528, 6992], [3670, 7441, 2566, 6402, 3704], [3670, 7441, 2566, 6402, 3145], [280, 9231, 1386, 2528, 4182], [5644, 4203, 1906, 6402]]


# Word embedding Representation

In [14]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as  np

In [24]:
#all sentences should have the same length durong embedding
sentence_length = 8
#param "pre" will add 0s beginning and make sentencs of same lengt
embedded_docs = pad_sequences(onehot_representation, padding = "pre", 
                              maxlen = sentence_length)
print(embedded_docs)

[[   0    0    0    0 9231 8594 2528 9298]
 [   0    0    0    0 9231 8594 2528 3828]
 [   0    0    0    0 9231 1493 2528 6992]
 [   0    0    0 3670 7441 2566 6402 3704]
 [   0    0    0 3670 7441 2566 6402 3145]
 [   0    0    0  280 9231 1386 2528 4182]
 [   0    0    0    0 5644 4203 1906 6402]]


In [25]:
dim = 15

In [28]:
model = Sequential()
model.add(Embedding(voc_size, 10 , input_length = sentence_length))
model.compile()

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [39]:
#this is the fetaure vector
type(model.predict(embedded_docs))

numpy.ndarray